baseURL: "http://localhost:1313/"
languageCode: "en-us"
theme: "minimal"
title: "Dev-Coach"

# Theme Params
params:
  accent: "blue"
  author: ""
  backgroundColor: "white"
  copyright: "Copyright 2021 - Carsten Lamm"
  description: "TDD, Testing, Programming and Learning"
  dateFormat: "January 2, 2006"
  font: "Open Sans, Helvetica, Arial, sans-serif"
  githubUsername: "#"
  highlight: false
  highlightLanguages: ["javascript"]
  highlightStyle: "gruvbox-dark"
  profilePic: 'profile_pic.jpg'
  showBorder: true
  css: ["custom.css"]
  js: ["custom.js"]

menu:
  main:
  - { name: "Home", url: "/", weight: 1 }
  - { name: "Posts", url: "/posts/", weight: 2 }
  - { name: "Snippets", url: "/snippets/", weight: 3 }
  - { name: "About", url: "/about", weight: 4 }
  icon:
    # name is the name of a font awesome icon
    # TODO extract used icons and remove library
    - { url: "https://twitter.com/FQ400", name: "twitter", weight: 3 }
    - { url: "https://github.com/FQ400/dev-coach-site", name: "github", weight: 2 }
    #- { url: "mailto:me@example.com", name: "envelope-o", weight: 1 }
  footer:
    - { name: "Imprint", url: "/imprint", weight: 1 }
